## Cargamos las Librerías:

In [1]:
import janitor
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
import numpy as np
import pandas as pd
import seaborn as sns
import session_info
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
pd.set_option('display.float_format', '{:.2f}'.format)

/home/barea/anaconda3/envs/analisis_exploratorio/lib/python3.9/site-packages/janitor/utils.py:84: FutureWarning: PandasArray has been renamed NumpyExtensionArray. Use that instead. This alias will be removed in a future version.
  @_expand_grid.register(pd.arrays.PandasArray)

## Establecemos los Parámetros de los Gráficos:

In [2]:
%matplotlib inline
sns.set_style(style='whitegrid')
sns.set_context(context='notebook')
plt.rcParams['figure.figsize'] = (11, 9.4)

gender_palette = {
    "Mujer": "violet", 
    "Hombre": "skyblue",
    "No especificado": "red"
}

## Cargamos el Conjunto de Datos:

In [3]:
homicidios = pd.read_csv('~/homicidios/data/raw/homicidios.csv')
homicidios

,ent_regis,mun_regis,tloc_regis,loc_regis,ent_resid,mun_resid,tloc_resid,loc_resid,ent_ocurr,mun_ocurr,...,complicaro,dia_cert,mes_cert,anio_cert,maternas,ent_ocules,mun_ocules,loc_ocules,razon_m,dis_re_oax
0,1,1,15,1,32,44,5,1,1,1,...,9,18,12,2022,NaN,88,888,8888,0,999
1,1,1,15,1,1,1,15,1,1,1,...,9,12,12,2022,NaN,88,888,8888,0,999
2,1,1,15,1,1,1,15,1,1,1,...,9,17,12,2022,NaN,88,888,8888,0,999
3,1,1,15,1,1,1,15,1,1,1,...,9,1,1,2023,NaN,88,888,8888,0,999
4,1,1,15,1,14,53,1,7777,1,1,...,8,22,12,2022,NaN,88,888,8888,0,999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799864,32,24,8,1,32,24,8,1,32,24,...,8,99,12,2023,NaN,88,888,8888,0,999
799865,32,56,13,1,32,56,13,1,32,56,...,8,5,6,2023,NaN,88,888,8888,0,999
799866,32,56,13,1,32,17,4,42,32,56,...,8,9,8,2023,NaN,88,888,8888,0,999
799867,32,56,13,1,32,17,13,1,32,56,...,8,19,9,2023,NaN,88,888,8888,0,999
799868,32,38,5,1,32,38,1,75,32,38,...,8,6,4,2023,NaN,88,888,8888,0,999

In [4]:
homicidios.shape

(799869, 74)

## Conocemos los Nombres de las Columnas:

In [5]:
homicidios['gramos'].value_counts()

gramos
8888    788688
9999      3236
600        569
1000        97
900         92
         ...
5406         1
973          1
1978         1
2251         1
796          1
Name: count, Length: 1043, dtype: int64

## Cargamos los Catálogos de Datos:

In [6]:
import os
import sys

### Establecemos el Uso Modular en el Proyecto:

In [7]:
sys.path.append(os.path.abspath(".."))

### Importamos la Función Modular:

In [8]:
from modules.aplicar_catalogos import aplicar_catalogos

### Guardamos la Dirección del Catálogo de Datos:

In [9]:
ruta_catalogos = os.path.expanduser("~/homicidios/data/codes/")

In [10]:
homicidios = aplicar_catalogos(homicidios, ruta_catalogos)

[!] Catálogo 'ent_regis.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'mun_regis.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'tloc_regis.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'loc_regis.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'ent_resid.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'mun_resid.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'tloc_resid.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'loc_resid.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'ent_ocurr.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'mun_ocurr.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'loc_ocurr.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'ent_nac.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'gramos.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'dia_ocurr.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'mes_ocurr.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'anio_ocur.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'dia_regis.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'mes_regis.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'anio_regis.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'dia_nacim.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'anio_nacim.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'anio_cert.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'maternas.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'ent_ocules.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'mun_ocules.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'loc_ocules.csv' no encontrado en /home/barea/homicidios/data/codes/.
[!] Catálogo 'dis_re_oax.csv' no encontrado en /home/barea/homicidios/data/codes/.

### Aplicamos la Función:

In [15]:
homicidios['gramos'].value_counts()

gramos
8888    788688
9999      3236
600        569
1000        97
900         92
         ...
5406         1
973          1
1978         1
2251         1
796          1
Name: count, Length: 1043, dtype: int64

In [11]:
homicidios

,ent_regis,mun_regis,tloc_regis,loc_regis,ent_resid,mun_resid,tloc_resid,loc_resid,ent_ocurr,mun_ocurr,...,complicaro,dia_cert,mes_cert,anio_cert,maternas,ent_ocules,mun_ocules,loc_ocules,razon_m,dis_re_oax
0,1,1,15,1,32,44,5,1,1,1,...,No especificada,Dieciocho días,Diciembre,2022,NaN,88,888,8888,NaN,999
1,1,1,15,1,1,1,15,1,1,1,...,No especificada,Doce días,Diciembre,2022,NaN,88,888,8888,NaN,999
2,1,1,15,1,1,1,15,1,1,1,...,No especificada,Diecisiete días,Diciembre,2022,NaN,88,888,8888,NaN,999
3,1,1,15,1,1,1,15,1,1,1,...,No especificada,Un día,Enero,2023,NaN,88,888,8888,NaN,999
4,1,1,15,1,14,53,1,7777,1,1,...,No aplica,Veintidós días,Diciembre,2022,NaN,88,888,8888,NaN,999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799864,32,24,8,1,32,24,8,1,32,24,...,No aplica,No especificado,Diciembre,2023,NaN,88,888,8888,NaN,999
799865,32,56,13,1,32,56,13,1,32,56,...,No aplica,Cinco días,Junio,2023,NaN,88,888,8888,NaN,999
799866,32,56,13,1,32,17,4,42,32,56,...,No aplica,Nueve días,Agosto,2023,NaN,88,888,8888,NaN,999
799867,32,56,13,1,32,17,13,1,32,56,...,No aplica,Diecinueve días,Septiembre,2023,NaN,88,888,8888,NaN,999
799868,32,38,5,1,32,38,1,75,32,38,...,No aplica,Seis días,Abril,2023,NaN,88,888,8888,NaN,999

In [12]:
(
    homicidios[
        'sexo'
    ]
    .value_counts(
        normalize= True
    )
)

sexo
Hombre            0.56
Mujer             0.44
No especificado   0.00
Name: proportion, dtype: float64

In [13]:
homicidios.groupby(['sexo', 'tipo_defun']).size().reset_index(name = 'Frecuencia')

               sexo                       tipo_defun  Frecuencia
0            Hombre                        Accidente       31101
1            Hombre      Enfermedad (Muerte natural)      378034
2            Hombre             Homicidio (Agresión)       28244
3            Hombre              Intervención legale          29
4            Hombre                        Se ignora        2016
5            Hombre  Suicidio (Lesión autoinfligida)        7310
6             Mujer                        Accidente        9132
7             Mujer      Enfermedad (Muerte natural)      337567
8             Mujer             Homicidio (Agresión)        3739
9             Mujer                        Se ignora         431
10            Mujer  Suicidio (Lesión autoinfligida)        1760
11  No especificado                        Accidente          49
12  No especificado      Enfermedad (Muerte natural)         150
13  No especificado             Homicidio (Agresión)         270
14  No especificado                        Se ignora          35
15  No especificado  Suicidio (Lesión autoinfligida)           2

In [14]:
(
    homicidios
    .groupby(
        ['sexo', 'anio_cert']
    )
    .size()
    .reset_index(name = 'Frecuencia')
)

              sexo  anio_cert  Frecuencia
0           Hombre       2022        6506
1           Hombre       2023      440228
2            Mujer       2022        5533
3            Mujer       2023      347096
4  No especificado       2022          25
5  No especificado       2023         481

In [16]:
(
    homicidios
    .groupby(
        ['sexo', 'donador']
    )
    .size()
    .reset_index(name = 'Frecuencia')
)

               sexo          donador  Frecuencia
0            Hombre               No        6204
1            Hombre        No aplica      439205
2            Hombre  No especificada        1039
3            Hombre               Sí         286
4             Mujer               No        3677
5             Mujer        No aplica      348214
6             Mujer  No especificada         552
7             Mujer               Sí         186
8   No especificado               No           7
9   No especificado        No aplica         497
10  No especificado  No especificada           2

In [18]:
(
    homicidios
    .groupby(['sexo', 'edad'])
    .size()
    .reset_index(name = 'Frecuencia')
    .sort_values(by = 'Frecuencia', ascending= False)
)

                sexo                             edad  Frecuencia
127           Hombre  Setenta y cinco años                   8706
132           Hombre  Setenta y seis años                    8657
280            Mujer  Ochenta y dos años                     8608
133           Hombre  Setenta y siete años                   8577
131           Hombre  Setenta y ocho años                    8563
..               ...                              ...         ...
396  No especificado  Nueve horas                               1
397  No especificado  Ochenta y cinco años                      1
398  No especificado  Ochenta y seis años                       1
399  No especificado  Ocho días                                 1
429  No especificado  Veintiún años                             1

[430 rows x 3 columns]

## Guardamos el DataFrame:

In [41]:
homicidios.to_csv("~/homicidios/data/preprocessed/homicidios_preprocessed.csv", index=False)