## Cargamos las Librerías:

In [1]:
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
import polars as pl
import pandas as pd
import seaborn as sns
import warnings
from typing import Optional
warnings.filterwarnings('ignore')
import pandas as pd
pd.set_option('display.float_format', '{:.2f}'.format)
import os
import sys

In [2]:
homicidios = pl.read_csv('~/homicidios/data/final/homicidios_final.csv')
homicidios

shape: (799_869, 62)
┌───────────┬───────────┬────────────┬────────────┬───┬──────────┬─────────┬───────────┬───────────┐
│ ent_regis ┆ ent_resid ┆ tloc_ocurr ┆ causa_def  ┆ … ┆ maternas ┆ razon_m ┆ estado_de ┆ estado_de │
│ ---       ┆ ---       ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---     ┆ funcion_r ┆ funcion_r │
│ i64       ┆ i64       ┆ str        ┆ str        ┆   ┆ str      ┆ str     ┆ egistrada ┆ esidencia │
│           ┆           ┆            ┆            ┆   ┆          ┆         ┆ ---       ┆ ---       │
│           ┆           ┆            ┆            ┆   ┆          ┆         ┆ str       ┆ str       │
╞═══════════╪═══════════╪════════════╪════════════╪═══╪══════════╪═════════╪═══════════╪═══════════╡
│ 1         ┆ 32        ┆ 500 000 a  ┆ Neumonía,  ┆ … ┆ null     ┆ null    ┆ Aguascali ┆ Zacatecas │
│           ┆           ┆ 999 999    ┆ no especif ┆   ┆          ┆         ┆ entes     ┆           │
│           ┆           ┆ habitantes ┆ icada      ┆   ┆          ┆         ┆           ┆           │
│ 1         ┆ 1         ┆ 500 000 a  ┆ Síndrome   ┆ … ┆ null     ┆ null    ┆ Aguascali ┆ Aguascali │
│           ┆           ┆ 999 999    ┆ de         ┆   ┆          ┆         ┆ entes     ┆ entes     │
│           ┆           ┆ habitantes ┆ dificultad ┆   ┆          ┆         ┆           ┆           │
│           ┆           ┆            ┆ respira…   ┆   ┆          ┆         ┆           ┆           │
│ 1         ┆ 1         ┆ 500 000 a  ┆ Enfermedad ┆ … ┆ null     ┆ null    ┆ Aguascali ┆ Aguascali │
│           ┆           ┆ 999 999    ┆ pulmonar   ┆   ┆          ┆         ┆ entes     ┆ entes     │
│           ┆           ┆ habitantes ┆ obstructiv ┆   ┆          ┆         ┆           ┆           │
│           ┆           ┆            ┆ …          ┆   ┆          ┆         ┆           ┆           │
│ 1         ┆ 1         ┆ 500 000 a  ┆ Desnutrici ┆ … ┆ null     ┆ null    ┆ Aguascali ┆ Aguascali │
│           ┆           ┆ 999 999    ┆ ón proteic ┆   ┆          ┆         ┆ entes     ┆ entes     │
│           ┆           ┆ habitantes ┆ ocalórica  ┆   ┆          ┆         ┆           ┆           │
│           ┆           ┆            ┆ …          ┆   ┆          ┆         ┆           ┆           │
│ 1         ┆ 14        ┆ 500 000 a  ┆ Cirrosis   ┆ … ┆ null     ┆ null    ┆ Aguascali ┆ Jalisco   │
│           ┆           ┆ 999 999    ┆ hepática   ┆   ┆          ┆         ┆ entes     ┆           │
│           ┆           ┆ habitantes ┆ alcohólica ┆   ┆          ┆         ┆           ┆           │
│ …         ┆ …         ┆ …          ┆ …          ┆ … ┆ …        ┆ …       ┆ …         ┆ …         │
│ 32        ┆ 32        ┆ 20 000 a   ┆ Síndrome   ┆ … ┆ null     ┆ null    ┆ Zacatecas ┆ Zacatecas │
│           ┆           ┆ 29 999     ┆ de         ┆   ┆          ┆         ┆           ┆           │
│           ┆           ┆ habitantes ┆ aspiración ┆   ┆          ┆         ┆           ┆           │
│           ┆           ┆            ┆ neonata…   ┆   ┆          ┆         ┆           ┆           │
│ 32        ┆ 32        ┆ 100 000 a  ┆ Kernicteru ┆ … ┆ null     ┆ null    ┆ Zacatecas ┆ Zacatecas │
│           ┆           ┆ 249 999    ┆ s, no espe ┆   ┆          ┆         ┆           ┆           │
│           ┆           ┆ habitantes ┆ cificado   ┆   ┆          ┆         ┆           ┆           │
│ 32        ┆ 32        ┆ 100 000 a  ┆ Síndrome   ┆ … ┆ null     ┆ null    ┆ Zacatecas ┆ Zacatecas │
│           ┆           ┆ 249 999    ┆ de         ┆   ┆          ┆         ┆           ┆           │
│           ┆           ┆ habitantes ┆ dificultad ┆   ┆          ┆         ┆           ┆           │
│           ┆           ┆            ┆ respira…   ┆   ┆          ┆         ┆           ┆           │
│ 32        ┆ 32        ┆ 100 000 a  ┆ Gastrosqui ┆ … ┆ null     ┆ null    ┆ Zacatecas ┆ Zacatecas │
│           ┆           ┆ 249 999    ┆ sis        ┆   ┆          ┆         ┆           ┆           │
│           ┆           ┆ habitantes ┆            ┆   ┆          ┆         ┆           ┆           │
│ 32        ┆ 32        ┆ 5 000 a 9  ┆ Insuficien ┆ … ┆ null     ┆ null    ┆ Zacatecas ┆ Zacatecas │
│           ┆           ┆ 999        ┆ cia respir ┆   ┆          ┆         ┆           ┆           │
│           ┆           ┆ habitantes ┆ atoria     ┆   ┆          ┆         ┆           ┆           │
│           ┆           ┆            ┆ del…       ┆   ┆          ┆         ┆           ┆           │
└───────────┴───────────┴────────────┴────────────┴───┴──────────┴─────────┴───────────┴───────────┘

In [5]:
gender_palette = {
    "Mujer": "violet", 
    "Hombre": "skyblue",
    "No especificado": "red"
}

## Las 10 Principales Motivos de Muerte en México:

In [6]:
(
    homicidios['causa_def']
    .value_counts()
    .sort(by = 'count', descending= True)
    .head(10)
)

shape: (10, 2)
┌─────────────────────────────────┬────────┐
│ causa_def                       ┆ count  │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ Infarto agudo del miocardio, s… ┆ 130456 │
│ Diabetes mellitus no insulinod… ┆ 34229  │
│ Neumonía, no especificada       ┆ 27039  │
│ Diabetes mellitus no insulinod… ┆ 18392  │
│ Diabetes mellitus no insulinod… ┆ 16464  │
│ Otras cirrosis del hígado y la… ┆ 16045  │
│ Enfermedad pulmonar obstructiv… ┆ 12036  │
│ Agresión con disparo de otras … ┆ 11708  │
│ Cirrosis hepática alcohólica    ┆ 9630   │
│ Diabetes mellitus no especific… ┆ 9456   │
└─────────────────────────────────┴────────┘

## Muertes por Tipo de Defunción en México:

In [7]:
(
    homicidios['tipo_defun']
    .value_counts()
    .sort(by = 'count', descending= True)
)

shape: (6, 2)
┌─────────────────────────────────┬────────┐
│ tipo_defun                      ┆ count  │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ Enfermedad (Muerte natural)     ┆ 715751 │
│ Accidente                       ┆ 40282  │
│ Homicidio (Agresión)            ┆ 32253  │
│ Suicidio (Lesión autoinfligida… ┆ 9072   │
│ Se ignora                       ┆ 2482   │
│ Intervención legale             ┆ 29     │
└─────────────────────────────────┴────────┘

## Muertes por Tipo de Defunción y Sexo en México:

In [8]:
(
    homicidios
    .group_by(
        ['sexo', 'tipo_defun']
    )
    .len()
    .rename(
        {'len': 'Frecuencia'}
    )
    .sort(by = 'Frecuencia', descending= True)
    .head(10)
)

shape: (10, 3)
┌────────┬─────────────────────────────────┬────────────┐
│ sexo   ┆ tipo_defun                      ┆ Frecuencia │
│ ---    ┆ ---                             ┆ ---        │
│ str    ┆ str                             ┆ u32        │
╞════════╪═════════════════════════════════╪════════════╡
│ Hombre ┆ Enfermedad (Muerte natural)     ┆ 378034     │
│ Mujer  ┆ Enfermedad (Muerte natural)     ┆ 337567     │
│ Hombre ┆ Accidente                       ┆ 31101      │
│ Hombre ┆ Homicidio (Agresión)            ┆ 28244      │
│ Mujer  ┆ Accidente                       ┆ 9132       │
│ Hombre ┆ Suicidio (Lesión autoinfligida… ┆ 7310       │
│ Mujer  ┆ Homicidio (Agresión)            ┆ 3739       │
│ Hombre ┆ Se ignora                       ┆ 2016       │
│ Mujer  ┆ Suicidio (Lesión autoinfligida… ┆ 1760       │
│ Mujer  ┆ Se ignora                       ┆ 431        │
└────────┴─────────────────────────────────┴────────────┘

## Muertes de Mujeres por Tipo de Defunción en México:

In [15]:
(
    homicidios
    .filter(pl.col('sexo') == 'Mujer')
    .group_by(
        ['sexo', 'tipo_defun']
    )
    .len()
    .rename(
        {'len': 'Frecuencia'}
    )
    .sort(by='Frecuencia', descending= True)
)

shape: (5, 3)
┌───────┬─────────────────────────────────┬────────────┐
│ sexo  ┆ tipo_defun                      ┆ Frecuencia │
│ ---   ┆ ---                             ┆ ---        │
│ str   ┆ str                             ┆ u32        │
╞═══════╪═════════════════════════════════╪════════════╡
│ Mujer ┆ Enfermedad (Muerte natural)     ┆ 337567     │
│ Mujer ┆ Accidente                       ┆ 9132       │
│ Mujer ┆ Homicidio (Agresión)            ┆ 3739       │
│ Mujer ┆ Suicidio (Lesión autoinfligida… ┆ 1760       │
│ Mujer ┆ Se ignora                       ┆ 431        │
└───────┴─────────────────────────────────┴────────────┘

## Principales Sitios donde Ocurrieron Homicidios de Mujeres:

In [12]:
(
homicidios
    .filter(
    (pl.col("tipo_defun") == "Homicidio (Agresión)") &
    (pl.col("sexo") == "Mujer")
    )
    .group_by(
        ['sitio_ocur', 'tipo_defun']
    )
    .len()
    .rename(
        {'len': 'Frecuencia'}
    )
    .sort(by = 'Frecuencia', descending= True)
)

shape: (11, 3)
┌───────────────────────┬──────────────────────┬────────────┐
│ sitio_ocur            ┆ tipo_defun           ┆ Frecuencia │
│ ---                   ┆ ---                  ┆ ---        │
│ str                   ┆ str                  ┆ u32        │
╞═══════════════════════╪══════════════════════╪════════════╡
│ Vía pública           ┆ Homicidio (Agresión) ┆ 1308       │
│ Otro lugar            ┆ Homicidio (Agresión) ┆ 745        │
│ Hogar                 ┆ Homicidio (Agresión) ┆ 703        │
│ No especificado       ┆ Homicidio (Agresión) ┆ 433        │
│ Secretaría de salud   ┆ Homicidio (Agresión) ┆ 278        │
│ …                     ┆ …                    ┆ …          │
│ Unidad médica privada ┆ Homicidio (Agresión) ┆ 52         │
│ Otra unidad pública   ┆ Homicidio (Agresión) ┆ 43         │
│ IMSS BIENESTAR        ┆ Homicidio (Agresión) ┆ 22         │
│ ISSSTE                ┆ Homicidio (Agresión) ┆ 14         │
│ PEMEX                 ┆ Homicidio (Agresión) ┆ 1          │
└───────────────────────┴──────────────────────┴────────────┘

## Muertes de Mujeres por Tipo de Defunción  y Sitio donde Ocurrieron en México:

In [10]:
(
    homicidios
    .filter(pl.col('sexo') == 'Mujer')
    .group_by([
        'tipo_defun', 'sitio_ocur'
    ]
    )
    .len()
    .rename(
        {'len': 'Frecuencia'}
    )
    .sort(by = 'Frecuencia', descending= True)
)

shape: (59, 3)
┌─────────────────────────────────┬──────────────────────────────┬────────────┐
│ tipo_defun                      ┆ sitio_ocur                   ┆ Frecuencia │
│ ---                             ┆ ---                          ┆ ---        │
│ str                             ┆ str                          ┆ u32        │
╞═════════════════════════════════╪══════════════════════════════╪════════════╡
│ Enfermedad (Muerte natural)     ┆ Hogar                        ┆ 174449     │
│ Enfermedad (Muerte natural)     ┆ IMSS                         ┆ 66104      │
│ Enfermedad (Muerte natural)     ┆ Secretaría de salud          ┆ 38801      │
│ Enfermedad (Muerte natural)     ┆ Unidad médica privada        ┆ 16893      │
│ Enfermedad (Muerte natural)     ┆ Otro lugar                   ┆ 13484      │
│ …                               ┆ …                            ┆ …          │
│ Accidente                       ┆ Secretaría de Marina (SEMAR) ┆ 5          │
│ Se ignora                       ┆ IMSS BIENESTAR               ┆ 4          │
│ Suicidio (Lesión autoinfligida… ┆ PEMEX                        ┆ 3          │
│ Homicidio (Agresión)            ┆ PEMEX                        ┆ 1          │
│ Se ignora                       ┆ PEMEX                        ┆ 1          │
└─────────────────────────────────┴──────────────────────────────┴────────────┘

## Principales Lugares donde Ocurrieron Homicidios en México:

In [11]:
(
    homicidios
    .filter(pl.col("tipo_defun") == "Homicidio (Agresión)")
    .group_by([
        "sitio_ocur", "tipo_defun"
    ])
    .len()
    .rename({'len': 'Frecuencia'})
    .sort('Frecuencia', descending = True)
    .head(10)
)

shape: (10, 3)
┌───────────────────────┬──────────────────────┬────────────┐
│ sitio_ocur            ┆ tipo_defun           ┆ Frecuencia │
│ ---                   ┆ ---                  ┆ ---        │
│ str                   ┆ str                  ┆ u32        │
╞═══════════════════════╪══════════════════════╪════════════╡
│ Vía pública           ┆ Homicidio (Agresión) ┆ 14292      │
│ Otro lugar            ┆ Homicidio (Agresión) ┆ 6112       │
│ No especificado       ┆ Homicidio (Agresión) ┆ 4152       │
│ Hogar                 ┆ Homicidio (Agresión) ┆ 2962       │
│ Secretaría de salud   ┆ Homicidio (Agresión) ┆ 2523       │
│ IMSS                  ┆ Homicidio (Agresión) ┆ 896        │
│ Otra unidad pública   ┆ Homicidio (Agresión) ┆ 496        │
│ Unidad médica privada ┆ Homicidio (Agresión) ┆ 395        │
│ IMSS BIENESTAR        ┆ Homicidio (Agresión) ┆ 233        │
│ ISSSTE                ┆ Homicidio (Agresión) ┆ 167        │
└───────────────────────┴──────────────────────┴────────────┘